### ISSUE TITLE
Automated hide / show options without custom javascript

### ISSUE THREAD

**Issue by teomaragakis** [devinsays/options-framework-theme#188]
I suggest using a new array item for checkboxes that hide other options. By passing the id of the element you want to hide as a parameter of the element that hides it, you could use `data-target` and not have to explicitly add the jQuery `.click` functions manually.

**Comment by devinsays** [comment]
I do like how twitter bootstrap does that, but the downside is that it would require extra params for the array- like "target" and "visibility". Any others? If implemented, I could also see additional feature requests like slide rather than fade or accordion style..

The benefit of keeping it as custom js is that it is infinitely more flexible and less work to maintain and test.

**Comment by teomaragakis** [comment]
The way I see it, you'd keep using the `'class' = 'hidden'` part in the setting you want to hide and just add something like a `'hides' = 'elementid'` to the array of the checkbox or multi-check you want to use as a toggle. I think it's much easier to add a parameter to an array rather than add JS. I would disagree with adding effects, but you are right, people will ask for that. I like the default way ti hides and shows perfectly well. You could use the wiki to add instructions on changes like this.

As far as maintenance goes, I'm no expert by any means, but it seems simple enough to me to keep clean and tidy.

**Comment by pingram3541** [comment]
Where do we find this default script?

-- edit --
Never mind, I found the js inside this theme's functions.php.  I was looking inside /inc/js - thx!

--update--
I had to change from an inline script in the head to use `wp_enqueue_script` method instead so that the jQuery dependency was met but of course this is theme dependent and one can also use vanilla js if they want but this is specifically because I am using a different theme.

--tip--
Just wanted to share for others like me that have only copied the options.php into their own theme/child-theme folders, they may have to do the same.

functions.php:
```
/**
 * Options Framework - Toggle Hidden
 * 
 * Adds scripts to admin theme options page
 **/
add_action( 'optionsframework_custom_scripts', 'mytheme_of_custom_scripts' );
function mytheme_of_custom_scripts() {
    wp_enqueue_script('mytheme-options-script', get_stylesheet_directory_uri() . '/js/options.js', array( 'jquery' ));
}
```

/js/options.js:
```
(function($){
    $('body').on('click', '#example_showhidden', function() {  
        //toggle hidden field via checkbox
        var $target = $('#section-example_text_hidden');
        if ( $(this).is(':checked') ) {
	    $target.removeClass('hidden');
	} else {
	    $target.addClass('hidden');
	}
    });
})(jQuery);
```
