### ISSUE TITLE
Subheadings and general styling

### ISSUE THREAD

**Issue by teomaragakis** [devinsays/options-framework-theme#189]
Would you be interested in me adding subheadings and restyling the panel a little bit?

**Comment by devinsays** [comment]
The goal with this framework is to match WordPress core styling as much as possible. What did you have in mind?

**Comment by teomaragakis** [comment]
I disagree with this approach. Of course it's your project, and it goes wherever you want it to go, but if you take the trouble of building something good, why not improve it as much as you can? Think WooCommerce for instance, their interfaces are a huge improvement on the WordPress way. They are clean, pretty and usable, without moving far away from core styling. I am suggesting you tried a better UX approach, which WordPress is still behind on.

The things I don't like in particular are the empty sidebar space on the right, and the fact that your only organizational option is tabs. Modern themes have a lot of settings and bigger needs. Subheadings (for me at least) is a must.

I would also move the description text either underneath the option title or in a little tooltip over a question mark icon. The active area for each setting is too narrow (what if I want an image selector with 7 images? It would break in two lines, while there is empty horizontal space).

A little bit irrelevant, but I do not want to spam you with different ideas in different posts: I would merge the theme and plugin projects in one, and either use different branches, or other projects (using the main project as a git submodule) for the plugin and theme implementations. I believe that 99% of users just copy and paste the `/inc` directory and just use the core in their themes.

Again, your code, your rules, but it's a pity not to improve on this amazing project in any possible way.

**Comment by devinsays** [comment]
You're welcome to fork it and build something that fits your needs a little better (a lot of people have done this). I'd love to see what you come up with when you finish.

Making the options page full width is possible by hooking in a little extra CSS. You could create subhead links having an "info" option at the top of each settings section.

Description text in WordPress generally goes below the option (and I like to follow UX convention there), but you can always hook in an "info" option with text if you feel options do need more explanation under the title.

Git submodule is a good idea, but there are some compatibility issues between the two. It's not possible to make breaking changes to the plugin version like it is with the theme version.

What'd I actually love to do is rewrite this code to be completely extensible (so additional options can be hooked in) and so that it could be used for plugins as well. Just haven't had the time for it.
